[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "î…"
Pamac-manager = "îœ“"
Alacritty = "ï„ "
kitty = "ï’‰"
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Code="îœŒ"
Spotify = "ï†¼"
Google-chrome = "ï‰¨"
Insomnia = "ï¬¥"
jetbrains-idea-ce = "îµ"
jetbrains-pycharm-ce = "îˆµ"
electron-mail = "ï›°"
Mailspring = "ïª"
Genymotion = "ï”²"
"Genymotion Player" = "ï˜œ"
Zathura = "ïœ¥"
Thunar = "ïŠ"
bluejeans-v2 = "ïªŸ"
# smile emoji
MyNiceProgram = "ğŸ˜›"

[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"

[general]
separator = " â”ƒ "
default_icon = "ï„‘"

[options]
remove_duplicates = true
use_instance = true
no_names = true
